---
name: General Discussion
about: Discuss anything related to ELIMS
---

## Topic

<!-- What do you want to discuss? -->

## Context

<!-- Provide some background or context -->

## Questions for the Community

<!-- What would you like feedback on? -->

-
-
-

## Additional Thoughts

<!-- Any other relevant information -->

---

**Let's discuss!**
