---
name: Ideas
about: Share ideas for new features, improvements, or changes
---

## The Idea

<!-- Clearly describe your idea -->

## Problem it Solves

<!-- What problem does this idea address? -->

## Benefits

<!-- Who benefits and how? -->

- **Users**:
- **Developers**:
- **Laboratory Staff**:
- **Administrators**:

## Potential Challenges

<!-- What challenges might we face implementing this? -->

## Alternatives

<!-- Are there other ways to achieve the same goal? -->

## Your Thoughts

<!-- Any additional thoughts or considerations? -->

---

**Note**: If this idea gains traction, it may become a formal feature request!
