---
name: Show and Tell
about: Show off what you've built with ELIMS
---

## What I Built

<!-- Give your project a catchy name and brief description -->

## The Story

<!-- What motivated you to build this? What problem does it solve? -->

## How It Works

<!-- Describe your implementation -->

## Key Features

<!-- What are the highlights? -->

-
-
-

## Screenshots/Demo

<!-- Show us what it looks like! -->

## Tech Stack

<!-- What technologies did you use? -->

- ELIMS version:
- Additional tools:
- Integrations:

## Challenges & Lessons

<!-- What challenges did you face? What did you learn? -->

## Links

<!-- Share your code, demo, blog post, etc. -->

- **Repository**:
- **Demo**:
- **Blog Post**:
- **Other**:

## Get Involved

<!-- Can others use, contribute to, or learn from your project? -->

- [ ] Open source (link above)
- [ ] Available for collaboration
- [ ] Looking for feedback
- [ ] Just sharing for inspiration

## Questions?

<!-- Invite the community to ask questions -->

Feel free to ask me anything about this project!

---

**Thanks for sharing with the community!**
