// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthCheckHealthGetResponse, RootGetResponse } from './types.gen';

export class DefaultService {
    /**
     * Health Check
     * Health check endpoint.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static healthCheckHealthGet(): CancelablePromise<HealthCheckHealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }

    /**
     * Root
     * Root endpoint.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static rootGet(): CancelablePromise<RootGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
}
