// This file is auto-generated by @hey-api/openapi-ts

export type HealthCheckHealthGetResponse = ({
    [key: string]: (string);
});

export type RootGetResponse = ({
    [key: string]: (string);
});
