---
name: Bug Report
about: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug']
assignees: []
---

## Bug Description

<!-- A clear and concise description of what the bug is -->

## Steps to Reproduce

<!-- Provide detailed steps to reproduce the behavior -->

1. Go to '...'
2. Click on '...'
3. Run command '...'
4. See error

## Expected Behavior

<!-- A clear description of what you expected to happen -->

## Actual Behavior

<!-- What actually happened instead -->

## Screenshots/Logs

<!-- If applicable, add screenshots or logs to help explain your problem -->

```
Paste logs here
```

## Environment

<!-- Please complete the following information -->

- **OS**: [e.g., Windows 11, Ubuntu 22.04, macOS 14]
- **Python Version**: [e.g., 3.13.0]
- **ELIMS Version**: [e.g., 0.0.1, commit hash, or branch]
- **Docker Version** (if applicable): [e.g., 24.0.0]
- **Browser** (for frontend issues): [e.g., Chrome 120, Firefox 121]

## Installation Method

<!-- How did you install ELIMS? -->

- [ ] Docker Compose
- [ ] Local development setup
- [ ] Other (please describe):

## Configuration

<!-- Any relevant configuration or environment variables -->

```yaml
# Paste relevant config here (remove sensitive data!)
```

## Additional Context

<!-- Add any other context about the problem here -->

## Possible Solution

<!-- If you have ideas on how to fix this, please share them -->

## Related Issues

<!-- Link any related issues or PRs -->

- Related to #
- Duplicate of #
