---
name: Feature Request
about: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['feature']
assignees: []
---

## Feature Description

<!-- A clear and concise description of the feature you'd like to see -->

## Problem Statement

<!-- Is your feature request related to a problem? Please describe -->
<!-- Example: I'm always frustrated when [...] -->

## Proposed Solution

<!-- Describe the solution you'd like -->

## Alternatives Considered

<!-- Describe any alternative solutions or features you've considered -->

## Use Cases

<!-- Describe specific use cases for this feature -->

1. As a [user type], I want to [do something] so that [reason]
2. ...

## Mockups/Examples

<!-- If applicable, add sketches, mockups, or examples from other projects -->

## Implementation Ideas

<!-- If you have technical ideas on how to implement this, share them here -->

## Acceptance Criteria

<!-- What needs to be true for this feature to be considered complete? -->

- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

## Impact

<!-- Who will benefit from this feature? -->

- [ ] End users
- [ ] Developers
- [ ] System administrators
- [ ] Laboratory staff
- [ ] Other:

## Priority

<!-- How important is this feature to you? -->

- [ ] Critical - Blocking my use of ELIMS
- [ ] High - Would significantly improve my workflow
- [ ] Medium - Would be nice to have
- [ ] Low - Just an idea

## Additional Context

<!-- Add any other context, screenshots, or references about the feature request here -->

## Contribution

<!-- Are you willing to contribute to this feature? -->

- [ ] I'm willing to submit a PR for this feature
- [ ] I can help with testing
- [ ] I can help with documentation
- [ ] I prefer someone else implements this

## Related Issues

<!-- Link any related issues or discussions -->

- Related to #
- Depends on #
