---
name: General Issue
about: Create a general issue that doesn't fit other categories
title: ''
labels: []
assignees: []
---

## Description

<!-- A clear and concise description of the issue -->

## Context

<!-- Why is this issue important? What's the context? -->

## Additional Information

<!-- Add any other relevant information here -->

## Related

<!-- Link any related issues, PRs, or discussions -->

- Related to #
- See also #
