name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13", "3.14"]

    name: Tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: |
          uv run pytest --cov=elims --cov-branch --cov-report=xml --cov-report=html --cov-report=term tests/

      - name: Upload coverage reports
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Upload coverage artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            htmlcov/
            coverage.xml
          retention-days: 30

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run formatter check
        run: uv run ruff format --check elims/ tests/

      - name: Run linter
        run: uv run ruff check elims/ tests/

      - name: Run type checker
        run: uv run mypy elims/ tests/

      - name: Run coverage
        run: uv run pytest --cov=elims --cov-branch --cov-report=xml --cov-report=html --cov-report=term tests/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@884b79409bbd464b2a59edc326a4b77dc56b2195 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package-build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [tests, code-quality]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Check package
        run: uv run twine check dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/
          retention-days: 30

  documentation-quality:
    name: Documentation Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Format markdown
        run: uv run mdformat docs/ README.md CODE_OF_CONDUCT.md CONTRIBUTING.md

      - name: Lint documentation
        run: uv run vale docs/
        continue-on-error: false

  deploy-documentation:
    name: Deploy Documentation
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    needs: [documentation-quality, package-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing to gh-pages
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Copy README.md to docs/
        run: cp -f README.md docs/index.md

      - name: Copy CONTRIBUTING.md to docs/
        run: cp -f CONTRIBUTING.md docs/contributing.md

      - name: Copy CODE_OF_CONDUCT.md to docs/
        run: cp -f CODE_OF_CONDUCT.md docs/code_of_conduct.md

      - name: Copy license.md to docs/
        run: cp -f LICENSE docs/license.md

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Optional: fetch gh-pages if it exists
          git fetch origin gh-pages || true

      - name: Build and deploy versions with mike
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            uv run mike deploy --push --update-aliases --remote origin --branch gh-pages dev latest
            uv run mike set-default --push --remote origin --branch gh-pages latest
          else
            VERSION=${GITHUB_REF#refs/tags/}
            echo "Building version: $VERSION"
            uv run mike deploy --push --update-aliases --remote origin --branch gh-pages "$VERSION" stable
            uv run mike set-default --push --remote origin --branch gh-pages stable
          fi

      - name: List deployed versions
        run: |
          uv run mike --version
          uv run mike list --remote origin --branch gh-pages || true

  deploy-package:
    name: Deploy Package
    if: startsWith(github.ref, 'refs/tags/')
    needs: [package-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-packages
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f7600683efdcb7656dec5b29656edb7bc586e597 # v1.10.3
        with:
          print-hash: true
